Repository LGCNS-PJT-EDU/EDU_BE, pull requests merged in 2025-04, with the labels that each got.

#1 chore: PR Template 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 👷chore

#10 EDU-77 chore: GitHub For Jira 커밋 메시지 연동
  build.gradle
  githooks-src/commit-msg
  githooks-src/prepare-commit-msg
Labels: 👷chore

#18 EDU-82 refactor: commit-msg-edit
  githooks-src/commit-msg
Labels: ♻️refactor

#43 EDU-16 test: 회원탈퇴 테스트 추가
  src/test/java/com/education/takeit/user/UserServiceTest.java
Labels: ✅test

#44 feat: spotless 적용 및 GithubActions Workflow 작성
  .github/workflows/integration.yml
  build.gradle
Labels: ✨feat

#45 chore: GithubActions workflow 수정
  src/main/resources/application-test.yml
  src/test/java/com/education/takeit/TakeitApplicationTests.java
Labels: 👷chore

#46 chore: 테스트 코드에 필요한 h2 의존성 추가
  .github/workflows/integration.yml
  build.gradle
Labels: 👷chore
