Repository LGCNS-PJT-EDU/EDU_BE, pull requests merged in 2025-06, with the labels that each got.

#201 Edu 485 feat: 면접시 선택할 수 있는 과목 조회 기능 추가
  src/main/java/com/education/takeit/interview/controller/InterviewController.java
  src/main/java/com/education/takeit/interview/dto/InterviewAllSubIdResDto.java
  src/main/java/com/education/takeit/interview/dto/SubjectInfo.java
  src/main/java/com/education/takeit/interview/service/InterviewService.java
  src/main/java/com/education/takeit/roadmap/repository/RoadmapRepository.java
  src/main/java/com/education/takeit/roadmap/repository/SubjectRepository.java
  src/main/java/com/education/takeit/user/entity/User.java
Labels: ✨feat

#214 EDU-502 test: kafka 프로듀서,컨슈머 테스트 코드 작성
  src/test/java/com/education/takeit/kafka/feedback/consumer/FeedbackFailKafkaConsumerTest.java
  src/test/java/com/education/takeit/kafka/feedback/consumer/FeedbackSuccessKafkaConsumerTest.java
  src/test/java/com/education/takeit/kafka/feedback/producer/FeedbackKafkaProducerTest.java
  src/test/java/com/education/takeit/kafka/recommand/consumer/RecomFailKafkaConsumerTest.java
  src/test/java/com/education/takeit/kafka/recommand/consumer/RecomSuccessKafkaConsumerTest.java
  src/test/java/com/education/takeit/kafka/recommand/producer/RecomKafkaProducerTest.java
Labels: ✅test

#217 Edu 506 be 면접 피드백 fast api 연결
  src/main/java/com/education/takeit/global/client/AIClient.java
  src/main/java/com/education/takeit/interview/dto/AiFeedbackReqDto.java
  src/main/java/com/education/takeit/interview/dto/InterviewAllReplyReqDto.java
  src/main/java/com/education/takeit/interview/dto/InterviewFeedbackResDto.java
  src/main/java/com/education/takeit/interview/service/InterviewService.java
  src/test/java/com/education/takeit/interview/service/InterviewServiceTest.java
Labels: ✨feat

#233 Edu 526 be 관리자 작업
  src/main/java/com/education/takeit/admin/controller/AdminController.java
  src/main/java/com/education/takeit/admin/dto/TotalUserFindResDto.java
  src/main/java/com/education/takeit/admin/service/AdminService.java
  src/main/java/com/education/takeit/global/config/SecurityConfig.java
  src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
  src/main/java/com/education/takeit/user/entity/User.java
  src/main/java/com/education/takeit/user/repository/UserRepository.java
  src/main/java/com/education/takeit/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/db/20250501.sql
Labels: ✨feat

#241 Edu 526 be 관리자 작업
  src/main/java/com/education/takeit/admin/controller/AdminController.java
  src/main/java/com/education/takeit/admin/dto/AdminContentResDto.java
  src/main/java/com/education/takeit/admin/dto/AdminExamResDto.java
  src/main/java/com/education/takeit/admin/dto/AdminSubjectResDto.java
  src/main/java/com/education/takeit/admin/service/AdminService.java
  src/main/java/com/education/takeit/exam/repository/ExamRepository.java
  src/main/java/com/education/takeit/global/config/SecurityConfig.java
  src/main/java/com/education/takeit/global/security/CustomUserDetails.java
  src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
  src/main/java/com/education/takeit/global/security/JwtUtils.java
  src/main/java/com/education/takeit/oauth/service/GoogleOAuthService.java
  src/main/java/com/education/takeit/oauth/service/KakaoOAuthService.java
  src/main/java/com/education/takeit/oauth/service/NaverOAuthService.java
  src/main/java/com/education/takeit/recommend/repository/TotalContentRepository.java
  src/main/java/com/education/takeit/roadmap/repository/SubjectRepository.java
  src/main/java/com/education/takeit/user/entity/Role.java
  src/main/java/com/education/takeit/user/entity/User.java
  src/main/java/com/education/takeit/user/repository/UserRepository.java
  src/main/java/com/education/takeit/user/service/UserServiceImpl.java
  src/test/java/com/education/takeit/oauth/service/GoogleOAuthServiceTest.java
  src/test/java/com/education/takeit/oauth/service/KakaoOAuthServiceTest.java
  src/test/java/com/education/takeit/oauth/service/NaverOAuthServiceTest.java
  src/test/java/com/education/takeit/user/UserServiceTest.java
Labels: ✨feat

#245 Edu 546 fix: HicariCP idle 값 50으로 수정 및 tomcat 타임 아웃 시간 2분으로 수정
  src/main/resources/application-dev.yml
  src/test/java/com/education/takeit/feedback/service/FeedbackServiceTest.java
  src/test/java/com/education/takeit/interview/service/InterviewServiceTest.java
  src/test/java/com/education/takeit/oauth/service/GoogleOAuthServiceTest.java
  src/test/java/com/education/takeit/oauth/service/KakaoOAuthServiceTest.java
  src/test/java/com/education/takeit/oauth/service/NaverOAuthServiceTest.java
  src/test/java/com/education/takeit/recommend/RecommendServiceTest.java
  src/test/java/com/education/takeit/user/UserServiceTest.java
Labels: 🐛fix

#256 Edu 553 be recommend 단위 테스트 수정
  src/test/java/com/education/takeit/recommend/RecommendServiceTest.java
Labels: ✅test

#258 EDU-552 test: 실패로그 관련 테스트코드 작성
  build.gradle
  src/main/java/com/education/takeit/admin/failLog/controller/AdminFailLogController.java
  src/main/java/com/education/takeit/exam/service/ExamService.java
  src/main/java/com/education/takeit/kafka/common/config/KafkaConsumerConfig.java
  src/main/java/com/education/takeit/kafka/common/config/KafkaProducerConfig.java
  src/main/java/com/education/takeit/kafka/recommend/consumer/RecomFailKafkaConsumer.java
  src/main/java/com/education/takeit/kafka/recommend/consumer/RecomSuccessKafkaConsumer.java
  src/main/java/com/education/takeit/kafka/recommend/dto/RecomFailDto.java
  src/main/java/com/education/takeit/kafka/recommend/dto/RecomRequestDto.java
  src/main/java/com/education/takeit/kafka/recommend/dto/RecomResultDto.java
  src/main/java/com/education/takeit/kafka/recommend/entity/RecomFailLog.java
  src/main/java/com/education/takeit/kafka/recommend/producer/RecomKafkaProducer.java
  src/main/java/com/education/takeit/kafka/recommend/recoverer/RecomFailRecoverer.java
  src/main/java/com/education/takeit/kafka/recommend/repository/RecomFailRepository.java
  src/main/java/com/education/takeit/kafka/recommend/service/RecomFailLogService.java
  src/main/java/com/education/takeit/recommend/service/RecommendService.java
  src/test/java/com/education/takeit/exam/service/ExamServiceTest.java
  src/test/java/com/education/takeit/kafka/feedback/service/FeedbackFailLogServiceTest.java
  src/test/java/com/education/takeit/kafka/recommend/consumer/RecomFailKafkaConsumerTest.java
  src/test/java/com/education/takeit/kafka/recommend/consumer/RecomSuccessKafkaConsumerTest.java
  src/test/java/com/education/takeit/kafka/recommend/producer/RecomKafkaProducerTest.java
  src/test/java/com/education/takeit/kafka/recommend/service/RecomFailLogServiceTest.java
  src/test/java/com/education/takeit/recommend/RecommendServiceTest.java
Labels: ✅test

#259 Edu 555 fix: feedbackService테스트 코드 커버리지 기준에 맞게 수정
  src/test/java/com/education/takeit/exam/service/ExamServiceTest.java
  src/test/java/com/education/takeit/feedback/service/FeedbackServiceTest.java
Labels: 🐛fix, ✅test

#260 EDU-554 test: exam 단위 테스트 코드 추가
  src/main/java/com/education/takeit/exam/service/ExamService.java
  src/test/java/com/education/takeit/exam/service/ExamServiceTest.java
Labels: ✅test

#261 EDU-530 feat: PreAuthorize 추가
  src/main/java/com/education/takeit/admin/failLog/controller/AdminFailLogController.java
Labels: ✨feat
