Repository LGCNS-PJT-EDU/EDU_BE, pull requests merged in 2025-05, with the labels that each got.

#50 EDU-246 test: 네이버 로그인 테스트 코드 수정
  src/main/java/com/education/takeit/user/entity/User.java
  src/test/java/com/education/takeit/oauth/service/NaverOAuthServiceTest.java
Labels: ✅test

#55 Edu 262 fix: 회원탈퇴 테스트 코드 수정
  src/main/java/com/education/takeit/user/controller/UserController.java
  src/main/java/com/education/takeit/user/service/UserService.java
  src/main/java/com/education/takeit/user/service/UserServiceImpl.java
  src/test/java/com/education/takeit/user/UserServiceTest.java
Labels: 🐛fix

#57 Edu 249 be 로드맵 기능 구현
  src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
  src/main/java/com/education/takeit/roadmap/repository/RoadmapManagementRepository.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
Labels: ✨feat

#61 Edu 89 개발 be 진단 서비스
  docker-compose.yml
  src/main/java/com/education/takeit/TakeitApplication.java
  src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
  src/main/java/com/education/takeit/diagnosis/dto/DiagnosisAnswerRequest.java
  src/main/java/com/education/takeit/diagnosis/dto/DiagnosisResponse.java
  src/main/java/com/education/takeit/diagnosis/dto/GroupedDiagnosisResponse.java
  src/main/java/com/education/takeit/diagnosis/entity/Choice.java
  src/main/java/com/education/takeit/diagnosis/entity/Diagnosis.java
  src/main/java/com/education/takeit/diagnosis/repository/DiagnosisRepository.java
  src/main/java/com/education/takeit/diagnosis/service/DiagnosisService.java
  src/main/java/com/education/takeit/global/config/SecurityConfig.java
  src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
  src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
  src/main/resources/db/20250501.sql
  src/main/resources/db/20250507.sql
Labels: ✨feat

#71 Edu 89 개발 be 진단 서비스
  src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
  src/main/java/com/education/takeit/diagnosis/entity/Diagnosis.java
  src/main/java/com/education/takeit/diagnosis/service/DiagnosisService.java
  src/main/java/com/education/takeit/global/dto/StatusCode.java
  src/test/java/com/education/takeit/diagnosis/service/DiagnosisServiceTest.java
Labels: 🐛fix, ♻️refactor

#72 Edu 279 be 코드 컨벤션 맞춰서 수정
  src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
  src/main/java/com/education/takeit/diagnosis/service/DiagnosisService.java
  src/main/java/com/education/takeit/global/dto/StatusCode.java
  src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
  src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
  src/main/java/com/education/takeit/roadmap/dto/RoadmapRequestDto.java
  src/main/java/com/education/takeit/roadmap/dto/RoadmapResponseDto.java
  src/main/java/com/education/takeit/roadmap/dto/RoadmapSaveResDto.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
  src/test/java/com/education/takeit/diagnosis/service/DiagnosisServiceTest.java
Labels: ♻️refactor

#74 Edu 280 be 사용자 로드맵 제공 기능 구현
  src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
  src/main/java/com/education/takeit/roadmap/dto/RoadmapFindResDto.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
  src/main/resources/db/20250501.sql
Labels: ✨feat

#77 EDU-281 test: 로드맵 생성 테스트 코드 작성
  src/main/resources/application-dev.yml
  src/test/java/com/education/takeit/roadmap/service/RoadmapCreateTest.java
Labels: ✅test

#84 Edu 298 be 회원가입 검증 로직 추가 필요
  build.gradle
  src/main/java/com/education/takeit/global/exception/GlobalExceptionHandler.java
  src/main/java/com/education/takeit/global/validator/password/PasswordValidator.java
  src/main/java/com/education/takeit/global/validator/password/ValidPassword.java
  src/main/java/com/education/takeit/user/controller/UserController.java
  src/main/java/com/education/takeit/user/dto/ReqSignupDto.java
  src/test/java/com/education/takeit/user/ReqSingupDtoTest.java
Labels: ✨feat, ✅test

#97 Edu 341 be 재진단 관련 기능 추가
  src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
  src/main/resources/application.yml
  src/test/java/com/education/takeit/roadmap/service/RoadmapCreateTest.java
Labels: ✨feat, ♻️refactor

#98 Edu 335 사전 평가 get api 연동
  .github/workflows/codeStyleCheck.yml
  .github/workflows/integration.yml
  src/main/java/com/education/takeit/exam/dto/ExamResDto.java
  src/main/java/com/education/takeit/exam/service/ExamService.java
  src/main/java/com/education/takeit/feedback/client/InternalClient.java
  src/main/java/com/education/takeit/feedback/service/FeedbackService.java
  src/main/java/com/education/takeit/global/client/AIClient.java
  src/main/java/com/education/takeit/global/dto/StatusCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/test/java/com/education/takeit/diagnosis/service/DiagnosisServiceTest.java
  src/test/java/com/education/takeit/feedback/service/FeedbackServiceTest.java
  src/test/java/com/education/takeit/roadmap/service/RoadmapCreateTest.java
Labels: 👷chore, ✨feat, ♻️refactor

#111 Edu 343 be 테스트 도구 적용
  src/main/java/com/education/takeit/roadmap/entity/RoadmapManagement.java
  src/main/java/com/education/takeit/roadmap/repository/RoadmapRepository.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
  src/main/java/com/education/takeit/roadmap/service/SubjectService.java
  src/main/resources/db/20250501.sql
Labels: ♻️refactor

#115 Edu 350 be roadmap entity의 user id를 roadmap management로 이동
  src/main/java/com/education/takeit/diagnosis/controller/DiagnosisController.java
  src/main/java/com/education/takeit/global/dto/StatusCode.java
  src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
  src/main/java/com/education/takeit/roadmap/dto/GuestRoadmapSaveReqDto.java
  src/main/java/com/education/takeit/roadmap/entity/Roadmap.java
  src/main/java/com/education/takeit/roadmap/entity/RoadmapManagement.java
  src/main/java/com/education/takeit/roadmap/repository/RoadmapManagementRepository.java
  src/main/java/com/education/takeit/roadmap/repository/RoadmapRepository.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
  src/main/java/com/education/takeit/roadmap/service/SubjectService.java
  src/main/resources/db/20250501.sql
Labels: ♻️refactor

#122 Edu 357 be 추천 컨텐츠 스크립트 작성
  src/main/java/com/education/takeit/recommend/entity/TotalContent.java
  src/main/java/com/education/takeit/recommend/entity/UserContent.java
  src/main/java/com/education/takeit/roadmap/controller/RoadmapController.java
  src/main/java/com/education/takeit/roadmap/entity/LectureAmount.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapTransactionalService.java
  src/main/resources/db/20250501.sql
Labels: ✨feat, ♻️refactor

#135 Edu 385 be exam 해설 추가
  src/main/java/com/education/takeit/diagnosis/entity/Diagnosis.java
  src/main/java/com/education/takeit/exam/controller/ExamController.java
  src/main/java/com/education/takeit/exam/dto/ExamAnswerDto.java
  src/main/java/com/education/takeit/exam/entity/Exam.java
  src/main/java/com/education/takeit/exam/repository/ExamRepository.java
  src/main/java/com/education/takeit/roadmap/service/RoadmapService.java
  src/main/java/com/education/takeit/solution/controller/SolutionController.java
  src/main/java/com/education/takeit/solution/dto/SolutionResDto.java
  src/main/java/com/education/takeit/solution/entity/UserExamAnswer.java
  src/main/java/com/education/takeit/solution/repository/SolutionRepository.java
  src/main/java/com/education/takeit/solution/repository/UserExamAnswerRepository.java
  src/main/java/com/education/takeit/solution/service/SolutionService.java
  src/main/resources/db/20250501.sql
Labels: ✨feat, ♻️refactor

#149 Edu 409 be 스크립트 수정
  src/main/resources/db/20250501.sql
Labels: ♻️refactor

#173 Edu 424 be 피드백 저장하는 메소드 생성 및 반영
  kafka-docker-compose.yml
  src/main/java/com/education/takeit/exam/service/ExamService.java
  src/main/java/com/education/takeit/kafka/config/KafkaConsumerConfig.java
  src/main/java/com/education/takeit/kafka/config/KafkaProducerConfig.java
  src/main/java/com/education/takeit/kafka/consumer/FeedbackFailKafkaConsumer.java
  src/main/java/com/education/takeit/kafka/consumer/FeedbackSuccessKafkaConsumer.java
  src/main/java/com/education/takeit/kafka/producer/FeedbackKafkaProducer.java
  src/main/java/com/education/takeit/kafka/recoverer/FeedbackFailRecoverer.java
Labels: ✨feat

#175 Edu 411 be 챗봇 기능 개발
  build.gradle
  src/main/java/com/education/takeit/chat/controller/ChatController.java
  src/main/java/com/education/takeit/chat/dto/ChatReqDto.java
  src/main/java/com/education/takeit/chat/dto/ChatResDto.java
  src/main/java/com/education/takeit/chat/entity/Chat.java
  src/main/java/com/education/takeit/chat/handler/StompHandler.java
  src/main/java/com/education/takeit/chat/handler/StompPrincipal.java
  src/main/java/com/education/takeit/chat/repository/ChatRepository.java
  src/main/java/com/education/takeit/chat/service/ChatService.java
  src/main/java/com/education/takeit/global/client/AIClient.java
  src/main/java/com/education/takeit/global/config/SecurityConfig.java
  src/main/java/com/education/takeit/global/config/WebConfig.java
  src/main/java/com/education/takeit/global/config/WebSocketConfig.java
  src/main/java/com/education/takeit/global/security/JwtAuthenticationFilter.java
  src/main/resources/db/20250501.sql
Labels: ✨feat

#177 EDU-411 feat: 사용자 채팅 기록 반환 기능 구현
  src/main/java/com/education/takeit/chat/controller/ChatbotController.java
  src/main/java/com/education/takeit/chat/dto/ChatFindResDto.java
  src/main/java/com/education/takeit/chat/repository/ChatRepository.java
  src/main/java/com/education/takeit/chat/service/ChatService.java
  src/main/java/com/education/takeit/global/config/WebConfig.java
  src/main/resources/db/20250501.sql
Labels: ✨feat, ♻️refactor
